# Generated by Django 3.1.7 on 2021-04-03 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.TextField()),
                ('name', models.CharField(max_length=200)),
                ('birthdate', models.DateField()),
                ('contact', models.IntegerField()),
                ('address', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('achievements', models.TextField()),
                ('certificate', models.TextField()),
                ('experience', models.TextField()),
                ('skills', models.TextField()),
                ('interest', models.TextField()),
                ('Reference', models.CharField(max_length=200)),
            ],
        ),
    ]
