# Generated by Django 3.1.7 on 2021-04-04 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automateJobFind', '0002_auto_20210404_0314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='Reference',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='achievements',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='certificate',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='experience',
        ),
        migrations.AddField(
            model_name='resume',
            name='acheivement3',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='resume',
            name='achievement1',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='resume',
            name='achievement2',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='resume',
            name='certificate1',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='resume',
            name='certificate2',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='resume',
            name='experience1',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='resume',
            name='experience2',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='resume',
            name='experience3',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='resume',
            name='reference',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='resume',
            name='address',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='resume',
            name='birthdate',
            field=models.DateField(default=''),
        ),
        migrations.AlterField(
            model_name='resume',
            name='contact',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='resume',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='resume',
            name='interest',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='resume',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='resume',
            name='skills',
            field=models.TextField(default=''),
        ),
    ]
