# Generated by Django 3.1.7 on 2021-04-04 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('automateJobFind', '0003_auto_20210404_1610'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resume',
            old_name='acheivement3',
            new_name='achievement3',
        ),
    ]
