# Generated by Django 3.1.7 on 2021-04-04 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automateJobFind', '0004_auto_20210404_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='achievement1',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='achievement2',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='achievement3',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='certificate2',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='experience1',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='experience2',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='experience3',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
